name: Build and push SonarQube image
on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.2

      - name: Build Docker image
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          push: true
          tags: lumacollins98/github-actions-repo/sonarqube:latest
          dockerfile: Dockerfile

      - name: Login to Docker registry
        uses: docker/login-action@v2.1.0
        with:
          registry: https://index.docker.io/v1/
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Push Docker image
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          push: true
          tags: lumacollins98/github-actions-repo/sonarqube:latest
