name: My Workflow

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  my-job:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Hello, world!"
